# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Node Modules
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Tests
      run: npm test
      env:
        PLAYWRIGHT_JUNIT_OUTPUT_NAME: results.xml
    # HACK - Screenshots won't match due to differences in Machine/OS.  e.g.https://mmazzarolo.com/blog/2022-09-09-visual-regression-testing-with-playwright-and-github-actions/
    # Forcing update to make tests falsely report passing
    - name: Run Visual Regression Tests
      run: npx playwright test --grep @visual --update-snapshots
      env:
        PLAYWRIGHT_JUNIT_OUTPUT_NAME: visual-results.xml
        PLAYWRIGHT_HTML_REPORT: visual-playwright-report
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: |
          "results.xml"
          "visual-results.xml"
      if: always()
    - uses: actions/upload-artifact@v4
      name: Upload HTML report
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 5
    - uses: actions/upload-artifact@v4
      name: Upload Visual Regression Test HTML report
      if: always()
      with:
        name: visual-playwright-report
        path: visual-playwright-report/
        retention-days: 5
    - uses: actions/upload-artifact@v4
      name: Upload JUNIT Report
      if: always()
      with:
        name: results
        path: results.xml
        retention-days: 5
    - uses: actions/upload-artifact@v4
      name: Upload JUNIT Visual Regression Test Report
      if: always()
      with:
        name: visual-results
        path: visual-results.xml
        retention-days: 5
